# Datenstrom Yellow extension

Extension: Private
Version: 1.0.1
Description: Support for password-protected pages.
Developer: Steffen Schultz
Contributor: Kanbeq
Tag: feature, page, private, security
DownloadUrl: https://github.com/schulle4u/yellow-private/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/schulle4u/yellow-private
DocumentationLanguage: en, de
Published: 2026-09-26 08:55:07
Status: maintained
system/workers/private.php: private.php, create, update
